### ISSUE TITLE
Configuration file support

### ISSUE THREAD

**Issue by SeanChao** [SeanChao/mirror-cache#15]
- [x] Rules: configure different rules based on different patterns [9236bc1](https://github.com/SeanChao/mirror-cache/commit/9236bc1f0b8d21f3f17425933be3135d5a5611d0)
- [x] General Config: port, cache path, database url, etc [daf9d98](https://github.com/SeanChao/mirror-cache/commit/daf9d98a6ba73b01434f1b3f04a65b8fc9200ece)
- ~Hot reloading~

**Comment by SeanChao** [comment]
# Configuration file format proposal

This is a YAML config file example:

```yaml
port: 9000
debug: true

redis:
  url: redis://localhost

rules:
  - path: "/pypi/simple/*"
    policy: "policy_ttl_60"
    upstream: "https://pypi.org/simple"
  - path: "/pypi-packages/*"
    policy: "policy_lru_1k"
    upstream: "https://files.pythonhosted.org/packages"

policies:
  - name: policy_ttl_60
    type: ttl
    timeout: 60
  - name: policy_lru_1k
    type: lru
    size: 1024
```

Configuration file parsing is based on [config-rs](https://github.com/mehcode/config-rs). Other formats like `JSON`, `TOML` are also supported.
